import {billOccurrence,csvRows,fingerprint,active,incomeKinds,uid,type State,type Transaction} from './model';
// Uploaded documents are one purchase candidate, never one transaction per OCR line.
export function parseDocument(text:string,account:string,scope:string):CaptureDraft[]{
 const lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean);
 const shopping=/add to cart|order samples|qualifying first order/i.test(text);
 const totals:string[]=[];const prices:string[]=[];
 for(let i=0;i<lines.length;i++){
  const line=lines[i];
  if(/subtotal|sub total|savings|discount|\boff\b|orders over|qualifying|shipping|cash tendered|change due/i.test(line))continue;
  const total=line.match(/\b(?:grand total|order total|total paid|amount paid|amount due|balance due|total)\s*[:$\s]*([\d,]+\.\d{2})(?!\d)/i)
   || (/^(?:grand total|order total|total paid|amount paid|amount due|balance due|total)\s*:?$/i.test(line)?lines[i+1]?.match(/^\$?\s*([\d,]+\.\d{2})$/):null);
  if(total)totals.push(total[1].replace(/,/g,''));
  for(const m of line.matchAll(/\$\s*([\d,]+\.\d{2})(?!\d)/g))prices.push(m[1].replace(/,/g,''));
 }
 const candidates=[...new Set(totals.length?totals:prices)];
 const amount=candidates.length===1?candidates[0]:'';
 let date=text.match(/\b\d{4}-\d{2}-\d{2}\b/)?.[0]||'';
 if(!date){const raw=text.match(/\b\d{1,2}\/\d{1,2}\/\d{4}\b/)?.[0];if(raw)try{date=parseDate(raw)}catch{}}
 if(!validDate(date)||shopping)date='';
 const vendor=shopping?'':lines.find(x=>/[a-z]{3}/i.test(x)&&!/^\d|receipt|total/i.test(x))?.slice(0,140)||'';
 return [{id:uid(),date,vendor,amount,kind:scope==='Business'?'Business':'Need',category:'Other',account,scope,type:'Transaction',include:false,warning:[shopping?'Product screenshot, not proof of payment. Confirm purchase, merchant and actual paid total before recording.':'Document draft: verify merchant, total and purchase date.',candidates.length>1?'Multiple possible totals: enter the correct amount.':!amount?'No reliable price found: enter the amount.':!totals.length?'Price detected; tax or shipping may be excluded.':'','Select Include draft only after review.'].filter(Boolean).join(' ')}];
}
export type CaptureDraft={id:string,date:string,vendor:string,amount:string,kind:string,category:string,account:string,scope:string,type:string,include:boolean,warning:string};
export function validDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!isNaN(Date.parse(value))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;}
export function addDays(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function parseDate(value:string,order='MDY'){if(validDate(value))return value;const m=value.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);if(!m)throw Error('Use YYYY-MM-DD or the selected date format.');const date=`${m[3]}-${(order==='DMY'?m[2]:m[1]).padStart(2,'0')}-${(order==='DMY'?m[1]:m[2]).padStart(2,'0')}`;if(!validDate(date))throw Error('Invalid calendar date.');return date;}
export function cents(value:string){const v=value.trim().replace(/[$,\s]/g,'').replace(/^\((.*)\)$/,'-$1');if(!/^[+-]?\d+(\.\d{1,2})?$/.test(v))throw Error('Enter an amount with at most two decimals.');const n=Math.round(Number(v)*100);if(!Number.isSafeInteger(n))throw Error('Amount is too large.');return n;}
export function classify(vendor:string,income=false){if(income)return {kind:'Other income',category:'Income'};if(/transfer|credit card payment|payment thank you/i.test(vendor))return {kind:'Transfer',category:'Other'};if(/refund/i.test(vendor))return {kind:'Refund',category:'Other'};if(/groc|kroger|whole foods/i.test(vendor))return {kind:'Need',category:'Groceries'};if(/coffee|dining|restaurant/i.test(vendor))return {kind:'Want',category:'Dining'};if(/electric|internet|utilities|water bill/i.test(vendor))return {kind:'Need',category:'Utilities'};if(/mortgage|rent/i.test(vendor))return {kind:'Need',category:'Housing'};return {kind:'Need',category:'Other'};}
export function parseCapture(text:string,today:string,account:string,scope:string):CaptureDraft[]{return text.split(/\n|;|\.\s+(?=[A-Z])/).filter(x=>x.trim()).map(line=>{const matches=[...line.matchAll(/\$\s*([\d,]+(?:\.\d{1,2})?)|\b(\d+(?:\.\d{1,2})?)\s*(?:dollars|usd)\b/gi)];if(!matches.length){const cleaned=line.replace(/\b\d{4}-\d{2}-\d{2}\b|\b\d{1,2}\/\d{1,2}\/\d{4}\b/g,' ');const bare=[...cleaned.matchAll(/(?<![\w.])([0-9]+(?:,[0-9]{3})*(?:\.[0-9]{1,2})?)(?![\w.]|\s*(?:%|sq|units|days|months))/gi)];if(bare.length===1&&/paid|spent|received|income|earned|cost|expense|salary/i.test(line))matches.push(bare[0]);}const raw=matches[0]?.[1]||matches[0]?.[2]||'';const iso=line.match(/\b\d{4}-\d{2}-\d{2}\b/)?.[0];const date=iso||( /yesterday/i.test(line)?addDays(today,-1):today);const income=/received|earned|salary|income/i.test(line);const inferred=classify(line,income);const type=/invoice/i.test(line)&&!income?'Invoice':/\bdue\b/i.test(line)?'Bill':'Transaction';const warning=[matches.length!==1?'Use exactly one dollar amount per entry.':'',iso&&!validDate(iso)?'Invalid date.':'',!iso&&/\bdue\b|last |tomorrow|\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/i.test(line)?'Choose the exact date.':'',inferred.kind==='Transfer'?'Select the destination account in Accounts after creating a transfer there. Exclude this draft to avoid duplication.':''].filter(Boolean).join(' ');return {id:uid(),date,vendor:line.replace(matches[0]?.[0]||'\0','').trim(),amount:raw.replace(/,/g,''),...inferred,account,scope,type,include:!warning,warning};});}
export function draftTransaction(d:CaptureDraft):Transaction{const amount=cents(d.amount);if(amount<=0||!validDate(d.date)||!d.vendor.trim()||!d.account.trim())throw Error('Every selected draft needs a description, valid date, account and positive amount.');return {id:d.id,date:d.date,vendor:d.vendor.trim(),amount,kind:d.kind,category:d.category,account:d.account,scope:d.scope as 'Personal'|'Business',review:true};}
export function duplicate(d:Transaction,s:State){return active(s).some(t=>fingerprint(t)===fingerprint(d)||(t.account===d.account&&t.amount===d.amount&&Math.abs(Date.parse(t.date)-Date.parse(d.date))<=86400000));}
export type Mapping={date:number,vendor:number,amount:number,debit:number,credit:number};
export function importCSV(text:string,map:Mapping,account:string,scope:string,order:string,positiveExpense:boolean){const rows=csvRows(text);return rows.slice(1).map((r,i):CaptureDraft=>{try{if(map.date<0||map.vendor<0||map.amount<0&&map.debit<0&&map.credit<0)throw Error('Map date, description and amount or debit/credit.');const date=parseDate((r[map.date]||'').trim(),order);const read=(idx:number)=>idx<0||!r[idx]?.trim()?0:cents(r[idx]);let amount=map.amount>=0?read(map.amount):Math.abs(read(map.credit))-Math.abs(read(map.debit));if(map.amount>=0&&positiveExpense)amount=-amount;const vendor=r[map.vendor]?.trim();if(!vendor||amount===0)throw Error('Missing description or zero amount.');return {id:uid(),date,vendor,amount:String(Math.abs(amount)/100),...classify(vendor,amount>0),account,scope,type:'Transaction',include:true,warning:''};}catch(e){return {id:uid(),date:'',vendor:`Row ${i+2}: ${r.join(' · ')}`,amount:'',kind:'Need',category:'Other',account,scope,type:'Transaction',include:false,warning:(e as Error).message}}});}
export function cashEffect(t:Transaction){return t.kind==='Transfer'?0:(incomeKinds.includes(t.kind)||t.kind==='Refund'?t.amount:-t.amount)}
export function forecast(s:State,today:string,opening:number,monthlyVariable:number,monthlyIncome:number,delay:number,includeInvoices:boolean,buffer:number,oneTime?:{date:string,amount:number}){let balance=opening;const events:{date:string,label:string,amount:number}[]=[];if(oneTime&&oneTime.date>today&&oneTime.date<=addDays(today,90))events.push({date:oneTime.date,label:'Planned one-time purchase',amount:-Math.abs(oneTime.amount)});for(let n=1;n<=90;n++){const date=addDays(today,n);const day=Number(date.slice(-2));const days=new Date(Number(date.slice(0,4)),Number(date.slice(5,7)),0).getDate();for(const b of s.bills)if(b.frequency==='Monthly'&&billOccurrence(b,date.slice(0,7)).date===date&&!b.paid.includes(date.slice(0,7))&&!b.skipped?.includes(date.slice(0,7)))events.push({date,label:b.name,amount:-billOccurrence(b,date.slice(0,7)).amount});for(const expected of s.expectedIncome||[])if(day===Math.min(expected.day,days))events.push({date,label:'Scheduled expected income: '+expected.name,amount:expected.amount});if(day===Math.min(28,days)&&monthlyIncome)events.push({date,label:'Assumed monthly income',amount:monthlyIncome});}if(includeInvoices)for(const i of s.invoices.filter(i=>!i.deletedAt&&i.status!=='Draft')){const remaining=i.amount-i.payments.reduce((n,p)=>n+p.amount,0);const due=addDays(i.due>today?i.due:today,Math.max(1,delay));if(remaining&&due<=addDays(today,90))events.push({date:due,label:'Expected invoice: '+i.client,amount:remaining});}const points=Array.from({length:90},(_,i)=>{const date=addDays(today,i+1);balance+=events.filter(e=>e.date===date).reduce((n,e)=>n+e.amount,0)-monthlyVariable/30;return {date,balance:Math.round(balance)}});return {points,events:events.sort((a,b)=>a.date.localeCompare(b.date)),low:points.reduce((a,b)=>b.balance<a.balance?b:a),shortfall:points.find(p=>p.balance<buffer)};}
